Homework 4 Task 1.Totjmyanin
iraedeus/spbu_sem2_DT pull request #6
Opened 2024-04-29 22:18 UTC by iraedeus

![file](https://github.com/iraedeus/sbpu_sem2/assets/144918156/ab09806c-f496-4b3c-a1b8-282cf2998b7f) - with multiprocessing
![file](https://github.com/iraedeus/sbpu_sem2/assets/144918156/96211fc2-f2dc-416d-8bf5-c81c30956679) - without multiprocessing

Based on the data on the graphs, we can conclude that multithreading is not the optimal solution, always inferior in speed to the classical implementation without threads. However, the multiprocessor solution speeds up the algorithm by as much as 2 times, achieving maximum acceleration with 4 processes

2024-05-20 16:21 UTC, SpirinEgor requested changes
Очень много дублирующейся логики, можно причесать и уменьшить код раза в 2

2024-05-20 16:21 UTC, SpirinEgor commented on src/homework/homework_4/main.py
> +    return output
```suggestion
    return vars(args)
```

2024-05-20 16:21 UTC, SpirinEgor commented on src/homework/homework_4/main.py
> +        func(*args)
Не очень понял, для чего такое отличие?

2024-05-20 16:21 UTC, SpirinEgor commented on src/homework/homework_4/main.py
> +            array = random.sample(range(-1000000, 1000000), size)
Кажется это не честно сравнение, надо хотя бы в рамках разного числа тредов один массив использовать.

2024-05-20 16:21 UTC, SpirinEgor commented on src/homework/homework_4/main.py
> +    num_of_tests = 1
Давай 3-5 раз хотя бы

2024-05-20 16:21 UTC, SpirinEgor commented on src/homework/homework_4/merge_sort.py
> +        thread.join()
В этом же 0 смысла, запустили и сразу ждем завершения. Никакого асинхронного исполнения тут нет

2024-05-20 21:48 UTC, iraedeus commented
![image](https://github.com/iraedeus/spbu_sem2_DT/assets/144918156/07f6ddc9-fd45-4579-8225-e280b859b2f2)
![image](https://github.com/iraedeus/spbu_sem2_DT/assets/144918156/67fad518-9651-4409-84a2-90a4faceec5a)

2024-05-20 21:53 UTC, iraedeus commented
![image](https://github.com/iraedeus/spbu_sem2_DT/assets/144918156/06fdfbbd-b788-404d-b196-a57a28b025ab)
![image](https://github.com/iraedeus/spbu_sem2_DT/assets/144918156/021b25f8-51b3-4e2f-9c13-c7ae701fd85e)

2024-05-26 10:12 UTC, SpirinEgor requested changes

2024-05-26 10:12 UTC, SpirinEgor commented on src/homework/homework_4/main.py
> +        func(*args)
Все еще этот же вопрос, чем отличаются args и почему нельзя сделать общий интерфейс?

2024-05-26 10:12 UTC, SpirinEgor commented on src/homework/homework_4/main.py
> +    output_time = np.array([])
Зачем нампай, чем тут обычный лист не угодил?

2024-05-26 10:12 UTC, SpirinEgor commented on src/homework/homework_4/main.py
> +    num_of_tests = 3
Это как будто бы аргумент функции должен быть

2024-05-26 10:12 UTC, SpirinEgor commented on src/homework/homework_4/main.py
> +    threads = input_data["thread_count"]
Я бы явно такое передавал в функцию, не через словарь

2024-05-26 10:12 UTC, SpirinEgor commented on src/homework/homework_4/main.py
> +def evaluate_time(func: Callable, args: list[Any], is_threading: bool) -> float:
Эта функция же вообще не используется...

2024-05-26 10:12 UTC, SpirinEgor commented on src/homework/homework_4/main.py
> +                func(args[0])
Страшно

2024-05-26 10:12 UTC, SpirinEgor commented on src/homework/homework_4/merge_sort.py
> +T = TypeVar("T", str, int, float)
1. Не то чтобы и очень нужно
2. Если и делать, то делать адекватно: ограничение на тип -- возможность сравнивать

2024-05-26 10:12 UTC, SpirinEgor commented on src/homework/homework_4/merge_sort.py
> +def multiprocess_merge_sort(arr: list[T], threads_cnt: int) -> list[T]:
Функция почти полностью копирует предыдущую, можно упростить

2024-05-26 10:12 UTC, SpirinEgor commented on src/homework/homework_4/merge_sort.py
> +    right_half = recursive_merge_sort(right_half)
Вот в этом месте можно параллелить, просто отправлять каждую половину в свой тред

2024-05-29 20:04 UTC, iraedeus commented
![image](https://github.com/iraedeus/spbu_sem2_DT/assets/144918156/4ad54466-c10b-4f2d-962e-0dffdae3a235)
![image](https://github.com/iraedeus/spbu_sem2_DT/assets/144918156/b4f269c7-e1c6-4296-9cb8-d3cc8e304075)

2024-05-30 10:16 UTC, merged